// Generated by CoffeeScript 2.5.1
// * Глабольный менедреж событий в АБС
AA.EV = function() {};

(function() {  //╒═════════════════════════════════════════════════════════════════════════╛
  // ■ IMPLEMENTATION.coffee
  //╒═════════════════════════════════════════════════════════════════════════╛
  //---------------------------------------------------------------------------
  var _;
  //@[DEFINES]
  _ = AA.EV;
  _.init = function() {
    "INIT ABS GEVENTS SUB SYSTEM".p();
    this.events = new AA.GEvents();
    return this._initABSGEvents();
  };
  _.subscribeFor = function(evName, listener) {
    return this.events.subscribeFor(evName, listener);
  };
  _.call = function(evName) {
    return this.events.call(evName);
  };
})();

(function() {  //╒═════════════════════════════════════════════════════════════════════════╛
  // ■ EVENTS.coffee
  //╒═════════════════════════════════════════════════════════════════════════╛
  //---------------------------------------------------------------------------
  var _;
  //@[DEFINES]
  _ = AA.EV;
  _._initABSGEvents = function() {
    // * Когда АБС ставиться на паузу
    this.events.register("PauseABS");
    // * Когда игрок начинает выбирать зону действия навыка
    this.events.register("PlayerSkillSelector");
    // * Когда выполнился (закончился) навык Projectile на карте
    // * Запрашивает очистку кеша
    this.events.register("MapSkillsRequestsClean");
    // * Смена события под курсором
    this.events.register("UnderMouseEventChanged");
  };
})();

// ■ END EVENTS.coffee
//---------------------------------------------------------------------------
