// Generated by CoffeeScript 2.5.1
// * Глабольный менедреж событий в АБС
AA.EV = function() {};

(function() {  //╒═════════════════════════════════════════════════════════════════════════╛
  // ■ IMPLEMENTATION.coffee
  //╒═════════════════════════════════════════════════════════════════════════╛
  //---------------------------------------------------------------------------
  var _;
  //@[DEFINES]
  _ = AA.EV;
  _.init = function() {
    "INIT ABS GEVENTS SUB SYSTEM".p();
    this.events = [];
    return this._initABSGEvents();
  };
  _.subscribeFor = function(evName, listener) {
    var ref;
    return (ref = this._getEventByName(evName)) != null ? ref.addListener(listener) : void 0;
  };
  _.call = function(evName) {
    var ref;
    return (ref = this._getEventByName(evName)) != null ? ref.call() : void 0;
  };
})();

(function() {  //╒═════════════════════════════════════════════════════════════════════════╛
  // ■ EVENTS.coffee
  //╒═════════════════════════════════════════════════════════════════════════╛
  //---------------------------------------------------------------------------
  var _;
  //@[DEFINES]
  _ = AA.EV;
  _._getEventByName = function(name) {
    return this.events.find(function(ev) {
      return ev.name === name;
    });
  };
  _._initABSGEvents = function() {
    // * Когда АБС ставиться на паузу
    this.events.push(new AA.GEvent("PauseABS"));
    //TODO: Проверить эти два на использование
    this.events.push(new AA.GEvent("PlayerTarget"));
    this.events.push(new AA.GEvent("PlayerChangeState"));
    // * Когда игрок начинает выбирать зону действия навыка
    this.events.push(new AA.GEvent("PlayerSkillSelector"));
    // * Когда выполнился (закончился) навык Projectile на карте
    // * Запрашивает очистку кеша
    this.events.push(new AA.GEvent("MapSkillsRequestsClean"));
    // * Смена события под курсором
    this.events.push(new AA.GEvent("UnderMouseEventChanged"));
  };
})();

// ■ END EVENTS.coffee
//---------------------------------------------------------------------------
