// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Interpreter.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Interpreter.prototype;
  (function() {    //TODO: WIKI создать страничку

    // * Управление АБС событиями
    // -----------------------------------------------------------------------
    // * Изменить параметр АА события (врага)
    _.aaChangeAIParam = function(paramName, newValue) {
      var char, e;
      try {
        if (this.eventId() <= 0) {
          return;
        }
        char = $gameMap.event(this.eventId());
        if (char == null) {
          return;
        }
        if (!char.isABS()) {
          return;
        }
        return char.aaChangeModelParam(paramName, newValue);
      } catch (error) {
        e = error;
        return AA.w(e);
      }
    };
    // * Выполнить SAction
    _.aaExecuteSAction = function(action) {
      var char, e;
      try {
        if (this.eventId() >= 0) {
          char = $gameMap.event(this.eventId());
        }
        return AA.SAaction.execute(action, char);
      } catch (error) {
        e = error;
        return AA.w(e);
      }
    };
    // * Получить опыт с данного события "врага"
    return _.aaGainExp = function() {
      var e;
      try {
        if (this.eventId() <= 0) {
          return;
        }
        uAPI.gainExpForEnemyEv(this.eventId());
      } catch (error) {
        e = error;
        AA.w(e);
      }
    };
  })();
  return;
})();

// ■ END Game_Interpreter.coffee
//---------------------------------------------------------------------------
// -----------------------------------------------------------------------
