// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Party.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Party.prototype;
  // * Отдельный метод, для проверок условий в плагине или дочерних плагинах (например AA.PP.isShowItemGainNotify())
  _.pIsCanShowItemNotify = function() {
    return AA.PP.isShowItemGainNotify();
  };
  _.pOnSomeItemBeenGained = function() {
    var e;
    if (!this.pIsCanShowItemNotify()) {
      return;
    }
    try {
      if ($gameTemp._pLastItemGainedToParty == null) {
        return;
      }
      if ($gameTemp._pLastItemGainedToParty[0] == null) {
        return;
      }
      if ($gameTemp._pLastItemGainedToParty[1] <= 0) {
        return;
      }
      this.aaShowNotifyForItemGain(...$gameTemp._pLastItemGainedToParty);
      //TODO: Это временно тут
      if (AA.PP.isAddNewItemOnPanelOnPickup()) {
        return this.aaAddGainedItemToPanel(...$gameTemp._pLastItemGainedToParty);
      }
    } catch (error) {
      //TODO: Занулять $gameTemp._pLastItemGainedToParty ?
      e = error;
      return KDCore.warning(e);
    }
  };
  _.aaShowNotifyForItemGain = function(item, count) {
    var char, e, popUpItem;
    try {
      if (!KDCore.Utils.isSceneMap()) {
        return;
      }
      if (count <= 0) {
        return;
      }
      if (item == null) {
        return;
      }
      // * Специальный флаг, чтобы скрыть Notify
      // * Этот флаг использует Map Inventory (когда снимаешь предмет)
      if ($gameTemp.aaNotNeedItemPopUpNotify === true) {
        return;
      }
      popUpItem = new AA.Sprite_PopTreasureItem();
      popUpItem.setItem(item, count);
      char = $gamePlayer.AASprite();
      //TODO: Сделать проверку на предыидущий предмет, если сразу одинаковый, то х2
      //TODO: Звук какой-нибудь когда вещь поднимаешь!
      if (char == null) {
        return;
      }
      // * Если нету, создаём
      if (char.aaTreasurePopEngine == null) {
        return char.aaTreasurePopEngine = new AA.PopTreasureController(char, popUpItem);
      // * Если есть, но закончился, то пересоздаём
      } else if (char.aaTreasurePopEngine.isEmtpy()) {
        char.aaTreasurePopEngine.stop();
        return char.aaTreasurePopEngine = new AA.PopTreasureController(char, popUpItem); // * Добавляем
      } else {
        return char.aaTreasurePopEngine.addItem(popUpItem);
      }
    } catch (error) {
      e = error;
      return AA.w(e);
    }
  };
  _.aaAddGainedItemToPanel = function(item, count) {
    if (!AA.Utils.isAAObject(item)) {
      return;
    }
    // * Новый предмет (т.е. раньше не было)
    if (this.numItems(item) === count) {
      // * Тут надо использовать idA
      if (!$gamePlayer.aaSkillsSet.isHaveItemOnPanel(item.idA)) {
        // * Тут используется обычный ID (так как конвертируется в методе)
        uAPI.setItemToPanel(item.id);
      }
    }
  };
})();

// ■ END Game_Party.coffee
//---------------------------------------------------------------------------
