// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Temp.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Temp.prototype;
  _._aaInitAILogicThreads = function() {
    if (this.__aaAILogicThreads == null) {
      return this.__aaAILogicThreads = {};
    }
  };
  _.aaRegisterAILogicThread = function(eventId) {
    var thread;
    "THREAD REGISTERED FOR".p(eventId);
    this._aaInitAILogicThreads();
    thread = setInterval((function() {
      var ev;
      if (!AA.isABSMap()) {
        return;
      }
      ev = $gameMap.event(eventId);
      if (ev != null) {
        return ev.aaUpdateAILogic();
      } else {
        return $gameTemp.aaClearAILogicThread(eventId);
      }
    }), 100);
    this.__aaAILogicThreads[eventId] = thread;
  };
  _.aaClearAILogicThread = function(eventId) {
    var thread;
    this._aaInitAILogicThreads();
    thread = this.__aaAILogicThreads[eventId];
    if (thread != null) {
      clearInterval(thread);
    }
    this.__aaAILogicThreads[eventId] = null;
  };
  _.aaClearAILogicThreads = function() {
    var key, ref, value;
    if (this.__aaAILogicThreads == null) {
      return;
    }
    ref = this.__aaAILogicThreads;
    for (key in ref) {
      value = ref[key];
      this.aaClearAILogicThread(key);
    }
  };
})();

// ■ END Game_Temp.coffee
//---------------------------------------------------------------------------
