// Generated by CoffeeScript 2.6.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Game_Event.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Game_Event.prototype;
  _._aaUpdateForNetwork = function() {
    if (!ANGameManager.isMapMaster()) {
      return;
    }
    return this.AAEntity()._updateDataObserver();
  };
})();

// ■ END Game_Event.coffee
//---------------------------------------------------------------------------
