// Generated by CoffeeScript 2.5.1
//╒═════════════════════════════════════════════════════════════════════════╛
// ■ Scene_Map.coffee
//╒═════════════════════════════════════════════════════════════════════════╛
//---------------------------------------------------------------------------
(function() {
  var _;
  //@[DEFINES]
  _ = Scene_Map.prototype;
  _.updateABS = function() {
    return this.aaUpdateMouseDetection();
  };
})();

// ■ END Scene_Map.coffee
//---------------------------------------------------------------------------
//@aaUpdateMapScroolByMouse() #TODO: доработать скролл (взять из AABS MV)
